#!/usr/bin/env node
// Regenerates derived files from the core sources:
//   examples/*.asm      from js/core/examples.js
//   docs/LANGUAGE.md    from js/core/isa.js
'use strict';
const fs = require('fs');
const path = require('path');
const BB = require('./load-core')();

const root = path.join(__dirname, '..');

fs.mkdirSync(path.join(root, 'examples'), { recursive: true });
for (const ex of BB.EXAMPLES) {
  fs.writeFileSync(path.join(root, 'examples', ex.file), ex.source);
}

const { INSTRUCTIONS, SENSORS, LANGUAGE_NOTES } = BB.ISA;
const C = BB.CONFIG;
const out = [];
out.push('# Battle Bot Assembly — Language Reference', '');
out.push('> Generated by `node tools/build.js` from `js/core/isa.js`. The same tables drive the assembler, the VM and the in-app reference.', '');
out.push('## Program structure', '');
for (const n of LANGUAGE_NOTES) out.push(`- ${n}`);
out.push('', '```asm', 'MyBot            ; line 1: the robot name', '.def RANGE 150   ; constant', 'loop:', '    SCAN 20', '    GET  R0, SCAN_DIST', '    CMP  R0, 0', '    JL   loop', '    FIRE', '    WAIT', '    JMP  loop', '```', '');
out.push('## Operands', '');
out.push('| Kind | Accepts |', '|---|---|');
out.push('| `dst` | register `R0`..`R7` or memory `[n]`, `[Rx]`, `[Rx+n]`, `[Rx-n]` |');
out.push('| `src` | anything `dst` accepts, plus a number or `.def` constant |');
out.push('| `target` | a label |');
out.push('| `sensor` | a sensor name (see below) |', '');
out.push('## Instructions', '');
let group = null;
for (const ins of INSTRUCTIONS) {
  if (ins.group !== group) {
    group = ins.group;
    out.push('', `### ${group}`, '', '| Instruction | Cycles | Description | Example |', '|---|---|---|---|');
  }
  const form = [ins.op, ins.args.join(', ')].filter(Boolean).join(' ');
  out.push(`| \`${form}\` | ${ins.cost} | ${ins.summary.replace(/\|/g, '\\|')} | \`${ins.example}\` |`);
}
out.push('', '## Sensors (read with `GET dst, SENSOR`)', '', '| Sensor | Meaning |', '|---|---|');
for (const s of SENSORS) out.push(`| \`${s.name}\` | ${s.desc} |`);
out.push('', '## Simulation constants', '', '| Constant | Value |', '|---|---|');
for (const [k, v] of Object.entries(C)) out.push(`| ${k} | ${v} |`);
out.push('');
fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs', 'LANGUAGE.md'), out.join('\n'));
console.log(`Wrote ${BB.EXAMPLES.length} examples and docs/LANGUAGE.md`);
