#!/usr/bin/env node
// Regenerates derived files from the core sources:
//   examples/*.asm      from js/core/examples.js
//   docs/LANGUAGE.md    from js/core/isa.js
'use strict';
const fs = require('fs');
const path = require('path');
const BB = require('./load-core')();

const root = path.join(__dirname, '..');

fs.mkdirSync(path.join(root, 'examples'), { recursive: true });
for (const ex of BB.EXAMPLES) {
  fs.writeFileSync(path.join(root, 'examples', ex.file), ex.source);
}

const { INSTRUCTIONS, SENSORS, LANGUAGE_NOTES } = BB.ISA;
const C = BB.CONFIG;
const out = [];
out.push('# Battle Bot Assembly — Language Reference', '');
out.push('> Generated by `node tools/build.js` from the language tables in `js/core/isa.js` and the reference sections in `tools/build.js`. Edit those sources, then regenerate this file. Instruction names, operand kinds, costs and sensor names are shared with the assembler and in-app reference.', '');
out.push('## Program structure', '');
for (const n of LANGUAGE_NOTES) out.push(`- ${n}`);
out.push('', '### Starter program', '', 'This stationary starter sweeps its turret until it finds an enemy, aims, and requests a shot. More advanced robots check alignment and lead moving targets.', '',
  '```asm', 'MyBot', '; Comments belong below the name line.', '.def SCAN_WIDTH 30', 'main:',
  '    SCAN SCAN_WIDTH', '    GET  R0, SCAN_DIST', '    CMP  R0, 0', '    JL   search',
  '    GET  R1, SCAN_ANGLE', '    AIM  R1', '    FIRE', '    WAIT', '    JMP  main',
  'search:', '    GET  R1, TURRET', '    ADD  R1, 15', '    AIM  R1', '    WAIT', '    JMP  main', '```', '');
out.push('## Operands', '');
out.push('| Kind | Accepts |', '|---|---|');
out.push('| `dst` | register `R0`..`R7` or memory `[n]`, `[Rx]`, `[Rx+n]`, `[Rx-n]` |');
out.push('| `src` | anything `dst` accepts, plus a number or `.def` constant |');
out.push('| `target` | a label or a numeric, zero-based instruction index; registers and constants are not accepted |');
out.push('| `sensor` | a sensor name (see below) |', '');
out.push('Instructions are indexed from 0, excluding the name, blank lines, comments, labels and directives. A target equal to the instruction count is legal and wraps to instruction 0; negative targets and targets beyond that count are assembly errors. Labels are usually easier to maintain than numeric targets.', '',
  'For memory operands, `Rx` means one of `R0`..`R7`. Offsets are numeric literals or constants; arbitrary expressions and multiple registers are not supported. Use `[R1-4]`, not `[R1+-4]`. In the instruction table, `dy` and `dx` in `ATAN2` and `a` and `b` in `CMP` accept any `src` operand.', '',
  '## Execution and robot commands', '',
  '- Registers, memory, the stack and the program counter belong to each robot. The stack starts empty and has 64 entries shared by `PUSH`/`POP` and `CALL`/`RET`. Balance your pushes and pops inside subroutines so `RET` retrieves its return address.',
  '- `CMP` is the only instruction that changes the comparison result. Arithmetic does not update it. The initial comparison is equal; use `CMP` explicitly before conditional jumps.',
  '- During each tick, living robots run their CPUs before any bodies move. `GET` reads current state; `SCAN` and `RADAR` update their result sensors immediately. Body and turret commands set desired targets, so `AIM 90` followed by `GET R0, TURRET` still reads the current turret angle.',
  '- After CPU execution, bodies and turrets turn, robots accelerate and move, collisions are resolved, requested shots are created, and projectiles move. A shot uses the turret angle after that tick\'s rotation. Repeating a movement or aiming command in a tick replaces its previous target; repeating `FIRE` requests at most one shot.',
  '- Desired speed and headings persist across ticks, `WAIT`, `HALT` and CPU faults. Absolute headings wrap into 0..359. `TURN` is relative to the current body heading, so repeated `TURN 90` commands do not add 90 degrees to the previous desired target.',
  `- At most one projectile is fired every ${C.FIRE_COOLDOWN} ticks. A shot sets the cooldown to ${C.FIRE_COOLDOWN}, then the world decrements it to ${C.FIRE_COOLDOWN - 1} before the next CPU tick. A \`FIRE\` request while cooling down is discarded rather than queued for a later tick.`,
  '- `RAND` uses the shared match random-number generator. Replaying requires the same seed, arena, roster order, rules and programs; another robot\'s random calls can change later random results.',
  '- Division/modulo by zero, an invalid memory address, stack underflow/overflow, a nonpositive `RAND` range, or a negative `SQRT` input faults the CPU and reports the instruction\'s source line.', '',
  '## Instructions');
let group = null;
for (const ins of INSTRUCTIONS) {
  if (ins.group !== group) {
    group = ins.group;
    out.push('', `### ${group}`, '', '| Instruction | Cycles | Description | Example |', '|---|---|---|---|');
  }
  const form = ins.op === 'ATAN2' ? 'ATAN2 dst, dy, dx' : ins.op === 'CMP' ? 'CMP a, b' : [ins.op, ins.args.join(', ')].filter(Boolean).join(' ');
  out.push(`| \`${form}\` | ${ins.cost} | ${ins.summary.replace(/\|/g, '\\|')} | \`${ins.example}\` |`);
}
out.push('', '## Sensors (read with `GET dst, SENSOR`)', '', '| Sensor | Meaning |', '|---|---|');
for (const s of SENSORS) out.push(`| \`${s.name}\` | ${s.desc} |`);
out.push('', '### Sensor result details', '',
  '- All sensor values are integers. Positions, distances, angles and speeds are rounded to the nearest integer, with halfway cases rounded toward positive infinity; health is rounded up. Angles are absolute arena angles unless stated otherwise.',
  '- `SCAN_*` values are a snapshot from the most recent `SCAN`, not a continuously updated track. They remain unchanged until another scan, even if the target moves or dies. `SCAN_ANGLE` is the absolute bearing; `SCAN_HEADING` is the target\'s body heading. A negative `SCAN_SPEED` means the target is reversing.',
  '- `THREAT_*` values likewise come from the most recent `RADAR`. `THREAT_ANGLE` is the bearing to the projectile; `THREAT_HEADING` is its travel direction. Radar tests projectile velocity toward your current position, without predicting your own future motion.',
  '- Before the first scan/radar call, and after a call finds nothing, the corresponding distance is -1 and all its other result fields are 0. Check the distance before using the other fields.',
  '- Teammates are excluded from `SCAN`, `RADAR` and `ENEMIES`. Their bullets pass through you. `ALLIES` excludes yourself. `FRONT` checks walls and obstacles only, using the full circular body, even near corners; it measures forward along body heading regardless of whether you are reversing.', '',
  '## Simulation constants', '',
  'These are default game settings in `js/core/isa.js`, not predefined assembly constants or sensors. To use a literal such as bullet speed in a program, define your own `.def` constant. Distances use arena units; a tick is one simulation step. Playback at 1× targets 60 ticks per second.', '',
  '| Constant | Value | Meaning / units |', '|---|---:|---|');
const meanings = {
  ARENA_W: 'Arena width, in units', ARENA_H: 'Arena height, in units', ROBOT_RADIUS: 'Circular collision radius, in units',
  MAX_HEALTH: 'Starting health', CYCLES_PER_TICK: 'Maximum CPU cycles per robot per tick', NUM_REGS: 'Number of registers',
  MEMORY_SIZE: 'Memory words', STACK_SIZE: 'Shared data/return stack entries', MAX_SPEED: 'Maximum forward units per tick',
  MAX_REVERSE: 'Minimum signed speed, in units per tick', ACCELERATION: 'Maximum speed change per tick',
  BODY_TURN_RATE: 'Maximum body degrees per tick', TURRET_TURN_RATE: 'Maximum turret degrees per tick',
  FIRE_COOLDOWN: 'Minimum ticks between shots', BULLET_SPEED: 'Projectile units per tick', BULLET_DAMAGE: 'Health lost per projectile hit',
  SCAN_MAX_WIDTH: 'Maximum full scan-cone width, in degrees', RADAR_RANGE: 'Maximum radar distance, in units',
  MAX_TICKS: 'Competitive match time limit, in ticks',
};
for (const [k, v] of Object.entries(C)) out.push(`| \`${k}\` | ${v} | ${meanings[k] || ''} |`);
out.push('', `At 0 health a robot is destroyed. In free-for-all, the last living robot wins; at the time limit, the living robot with highest health wins, with an equal-health tie producing a draw. Team matches use the last surviving team or highest total living-team health, with a tie producing a draw. Browser practice without an opponent has no victory/time-limit check; the CLI stops practice runs after ${C.MAX_TICKS} ticks.`);
out.push('');
fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs', 'LANGUAGE.md'), out.join('\n'));
console.log(`Wrote ${BB.EXAMPLES.length} examples and docs/LANGUAGE.md`);
