#!/usr/bin/env node
// Regenerates derived files from the core sources:
//   examples/*.asm      from js/core/examples.js
//   docs/LANGUAGE.md    from js/core/isa.js
'use strict';
const fs = require('fs');
const path = require('path');
const BB = require('./load-core')();

const root = path.join(__dirname, '..');

fs.mkdirSync(path.join(root, 'examples'), { recursive: true });
for (const ex of BB.EXAMPLES) {
  fs.writeFileSync(path.join(root, 'examples', ex.file), ex.source);
}

const { INSTRUCTIONS, SENSORS, LANGUAGE_NOTES } = BB.ISA;
const C = BB.CONFIG;
const out = [];
out.push('# Battle Bot Assembly — Language Reference', '');
out.push('> Generated by `node tools/build.js` from the language tables in `js/core/isa.js` and the reference sections in `tools/build.js`. Edit those sources, then regenerate this file. Instruction names, operand kinds, costs and sensor names are shared with the assembler and in-app reference.', '');
out.push('## Program structure', '');
for (const n of LANGUAGE_NOTES) out.push(`- ${n}`);
out.push('', '### Appearance header', '', 'Choose up to three cosmetic presets immediately below the name. Comments and blank lines may appear between them. Values and directive names are case-insensitive. Each directive may appear once, before any label, constant or instruction. Omitted settings use the defaults below.', '',
  '| Directive | Presets | Default |', '|---|---|---|');
for (const [key, spec] of Object.entries(BB.ISA.APPEARANCE)) out.push(`| \`.${key} preset\` | ${spec.choices.map((v) => `\`${v}\``).join(', ')} | \`${spec.default}\` |`);
out.push('', '```asm', 'Iron Beetle', '.shape hexagon', '.drive wheels', '.turret twin', '', 'main:', '    WAIT', '    JMP main', '```', '',
  'Appearance directives are metadata, not executable instructions: they consume no CPU cycles and do not change instruction indices. Collision radius, movement, health, bullet origin, fire rate and damage remain identical for every preset. A twin turret still fires one projectile per shot. Settings travel with the `.asm` file and take effect on Apply, including a program reload during a match.');
out.push('', '#### Hull shapes: `.shape`', '',
  'The hull rotates with your body heading (`HEADING`). The turret continues to rotate independently. These presets change the visible body outline; the physical hitbox stays a circle with radius 16.', '',
  '| Preset | Appearance |', '|---|---|',
  '| `tank` | The original compact rectangular hull with rounded corners. Default. |',
  '| `circle` | A round hull around the turret. Headlights still indicate the front. |',
  '| `hexagon` | A six-sided hull with a point facing forward and another facing backward. |',
  '| `wedge` | A pointed nose facing forward with a broad rear. |', '',
  '#### Drive styles: `.drive`', '',
  'The drive is drawn beneath the hull and follows the body heading. Every style uses the same speed limits, acceleration, turning and terrain collisions.', '',
  '| Preset | Appearance |', '|---|---|',
  '| `tracks` | Two dark side treads with tread marks that scroll with movement. Default. |',
  '| `wheels` | Four small wheels, two along each side of the hull. |',
  '| `hover` | An oval platform with a colored rim beneath the hull. It still collides with walls, obstacles and other robots; it does not fly over them. |', '',
  '#### Turret styles: `.turret`', '',
  'The turret follows `TURRET` and your `AIM` commands independently of the hull. These settings change the barrel drawing, not the weapon or its aiming speed.', '',
  '| Preset | Appearance |', '|---|---|',
  '| `standard` | One full-length barrel on the central turret dome. Default. |',
  '| `short` | One shorter barrel on the same dome. Range, bullet speed, damage and bullet origin are unchanged. |',
  '| `twin` | Two parallel full-length barrels. Each successful FIRE still creates one projectile from the normal central bullet origin, with the normal cooldown. |', '',
  'All 36 combinations are supported. Team/roster colors are assigned by the game; these directives do not select paint colors. Hit flashes follow your hull shape, and wrecks retain your selected hull, drive and turret.', '',
  '#### Header syntax and defaults', '',
  '- Put the robot name alone on line 1. Appearance directives belong in the header below it, before the first label, constant definition or executable instruction. They are not required to occupy literal lines 2, 3 and 4: comments and blank lines may intervene.',
  '- Directives can appear in any order. Use one literal preset word after each directive, separated by whitespace: `.shape circle`. Do not add commas or quotes, or use a register or `.def` constant in place of the preset.',
  '- Case does not matter: `.SHAPE HEXAGON` and `.shape hexagon` mean the same thing. Inline comments work normally, such as `.drive wheels ; four wheels`.',
  '- Specify each directive at most once. Repeating a setting is an assembly error even when both values are identical. Unsupported, missing or extra preset words are also errors, reported at their source line.',
  '- Every omitted setting receives its default independently: `tank`, `tracks`, `standard`. Existing robot files without an appearance header keep the original look. A file still needs at least one executable instruction after its name/header.', '',
  'For example, this changes only the drive. The hull remains `tank` and the turret remains `standard`:', '',
  '```asm', 'Wheel Scout', '; Appearance may be separated from the name by comments.', '.drive wheels ; leave the other two settings at their defaults', '', '.def CRUISE 3', 'main:', '    SPEED CRUISE', '    WAIT', '    JMP main', '```', '',
  '| Invalid header | Reason |', '|---|---|',
  '| `.shape triangle` | `triangle` is not one of the four hull presets. |',
  '| `.drive` | A preset is required. |',
  '| `.turret twin extra` | Only one preset word is accepted. |',
  '| `.shape circle` repeated later | Each appearance directive may appear only once. |',
  '| `.drive hover` after `.def CRUISE 3` or `main:` | The appearance header has already ended. Move the directive above constants and labels. |', '',
  '#### Saving, applying and resetting', '',
  'Appearance is part of the source text. Save .asm exports it, Load .asm reads it, and duplication copies it with the robot program. The browser also saves your source and draft with the roster.', '',
  'Typing a change edits the draft; press Apply to use it. Applying valid code before a match begins resets the arena. During an unfinished match, a robot already in the arena receives the new appearance and a fresh CPU while keeping its position and health. This is the same program-reload behavior as any other Apply, including resetting registers, memory and the stack. An invalid header prevents Apply and leaves the previously applied code and appearance active. Reset uses the last applied settings; Revert restores the last applied source in the editor.', '',
  '#### Built-in example combinations', '', '| Robot | Shape | Drive | Turret |', '|---|---|---|---|');
for (const ex of BB.EXAMPLES) {
  const { name, appearance } = BB.assemble(ex.source);
  out.push(`| ${name} | \`${appearance.shape}\` | \`${appearance.drive}\` | \`${appearance.turret}\` |`);
}
out.push('', '#### Stack tutorial bot', '',
  'Load [Stacker](../examples/stacker.asm) from the Add example menu to see explicit stack use during a match. It patrols cautiously and sweeps its turret for targets, with separate routines for movement, wall checks, turning, aiming and firing.', '',
  'The nested gun path is `main → combat → shoot_if_aligned → angle_error`. Each `CALL` pushes a return instruction index; each routine then uses `PUSH` to save the registers it needs as scratch space. `POP` restores them in reverse order before `RET` pops the return address. The deepest gun path holds 11 entries: 3 return addresses plus 8 saved register values.', '',
  'The wall path, `main → drive → wall_check → steer_away`, peaks at 10 entries. Every path returns with balanced saves and restores. The stack is empty at the main loop\'s `WAIT`, `R6` counts completed patrol/gun passes, and `R7` keeps the cruise speed. A CPU budget boundary can pause a routine with values still on the stack; they remain available on the next tick. The comparison result is not a register and is not saved by `PUSH`, so branches perform a fresh `CMP` after helpers return.', '',
  'Use Step with the CPU inspector to watch stack depth and the next source line. One Step advances a whole simulation tick, which can execute up to 50 CPU cycles; it does not stop after each individual PUSH or POP.');
out.push('', '### Starter program', '', 'This stationary starter sweeps its turret until it finds an enemy, aims, and requests a shot. More advanced robots check alignment and lead moving targets.', '',
  '```asm', 'MyBot', '; Comments belong below the name line.', '.def SCAN_WIDTH 30', 'main:',
  '    SCAN SCAN_WIDTH', '    GET  R0, SCAN_DIST', '    CMP  R0, 0', '    JL   search',
  '    GET  R1, SCAN_ANGLE', '    AIM  R1', '    FIRE', '    WAIT', '    JMP  main',
  'search:', '    GET  R1, TURRET', '    ADD  R1, 15', '    AIM  R1', '    WAIT', '    JMP  main', '```', '');
out.push('## Operands', '');
out.push('| Kind | Accepts |', '|---|---|');
out.push('| `dst` | register `R0`..`R7` or memory `[n]`, `[Rx]`, `[Rx+n]`, `[Rx-n]` |');
out.push('| `src` | anything `dst` accepts, plus a number or `.def` constant |');
out.push('| `target` | a label or a numeric, zero-based instruction index; registers and constants are not accepted |');
out.push('| `sensor` | a sensor name (see below) |', '');
out.push('Instructions are indexed from 0, excluding the name, blank lines, comments, labels and directives. A target equal to the instruction count is legal and wraps to instruction 0; negative targets and targets beyond that count are assembly errors. Labels are usually easier to maintain than numeric targets.', '',
  'For memory operands, `Rx` means one of `R0`..`R7`. Offsets are numeric literals or constants; arbitrary expressions and multiple registers are not supported. Use `[R1-4]`, not `[R1+-4]`. In the instruction table, `dy` and `dx` in `ATAN2` and `a` and `b` in `CMP` accept any `src` operand.', '',
  '## Execution and robot commands', '',
  '- Registers, memory, the stack and the program counter belong to each robot. The stack starts empty and has 64 entries shared by `PUSH`/`POP` and `CALL`/`RET`. Balance your pushes and pops inside subroutines so `RET` retrieves its return address.',
  '- `CMP` is the only instruction that changes the comparison result. Arithmetic does not update it. The initial comparison is equal; use `CMP` explicitly before conditional jumps.',
  '- During each tick, living robots run their CPUs before any bodies move. `GET` reads current state; `SCAN` and `RADAR` update their result sensors immediately. Body and turret commands set desired targets, so `AIM 90` followed by `GET R0, TURRET` still reads the current turret angle.',
  '- After CPU execution, bodies and turrets turn, robots accelerate and move, collisions are resolved, requested shots are created, and projectiles move. A shot uses the turret angle after that tick\'s rotation. Repeating a movement or aiming command in a tick replaces its previous target; repeating `FIRE` requests at most one shot.',
  '- Desired speed and headings persist across ticks, `WAIT`, `HALT` and CPU faults. Absolute headings wrap into 0..359. `TURN` is relative to the current body heading, so repeated `TURN 90` commands do not add 90 degrees to the previous desired target.',
  `- At most one projectile is fired every ${C.FIRE_COOLDOWN} ticks. A shot sets the cooldown to ${C.FIRE_COOLDOWN}, then the world decrements it to ${C.FIRE_COOLDOWN - 1} before the next CPU tick. A \`FIRE\` request while cooling down is discarded rather than queued for a later tick.`,
  '- Each robot\'s `RAND` draws from its own random-number stream, seeded from the match seed and the robot\'s roster slot, so another robot\'s random calls never change your results. Replaying requires the same seed, arena, roster order, rules and programs.',
  '- Division/modulo by zero, an invalid memory address, stack underflow/overflow, a nonpositive `RAND` range, or a negative `SQRT` input faults the CPU and reports the instruction\'s source line.', '',
  '## Instructions');
let group = null;
for (const ins of INSTRUCTIONS) {
  if (ins.group !== group) {
    group = ins.group;
    out.push('', `### ${group}`, '', '| Instruction | Cycles | Description | Example |', '|---|---|---|---|');
  }
  const form = ins.op === 'ATAN2' ? 'ATAN2 dst, dy, dx' : ins.op === 'CMP' ? 'CMP a, b' : [ins.op, ins.args.join(', ')].filter(Boolean).join(' ');
  out.push(`| \`${form}\` | ${ins.cost} | ${ins.summary.replace(/\|/g, '\\|')} | \`${ins.example}\` |`);
}
out.push('', '## Sensors (read with `GET dst, SENSOR`)', '', '| Sensor | Meaning |', '|---|---|');
for (const s of SENSORS) out.push(`| \`${s.name}\` | ${s.desc} |`);
out.push('', '### Sensor result details', '',
  '- All sensor values are integers. Positions, distances, angles and speeds are rounded to the nearest integer, with halfway cases rounded toward positive infinity; health is rounded up. Angles are absolute arena angles unless stated otherwise.',
  '- `SCAN_*` values are a snapshot from the most recent `SCAN`, not a continuously updated track. They remain unchanged until another scan, even if the target moves or dies. `SCAN_ANGLE` is the absolute bearing; `SCAN_HEADING` is the target\'s body heading. A negative `SCAN_SPEED` means the target is reversing.',
  '- `THREAT_*` values likewise come from the most recent `RADAR`. `THREAT_ANGLE` is the bearing to the projectile; `THREAT_HEADING` is its travel direction. Radar tests projectile velocity toward your current position, without predicting your own future motion.',
  '- Before the first scan/radar call, and after a call finds nothing, the corresponding distance is -1 and all its other result fields are 0. Check the distance before using the other fields.',
  '- Teammates are excluded from `SCAN`, `RADAR` and `ENEMIES`. Their bullets pass through you. `ALLIES` excludes yourself. `FRONT` checks walls and obstacles only, using the full circular body, even near corners; it measures forward along body heading regardless of whether you are reversing.', '',
  '## Simulation constants', '',
  'These are default game settings in `js/core/isa.js`, not predefined assembly constants or sensors. To use a literal such as bullet speed in a program, define your own `.def` constant. Distances use arena units; a tick is one simulation step. Playback at 1× targets 60 ticks per second.', '',
  '| Constant | Value | Meaning / units |', '|---|---:|---|');
const meanings = {
  ARENA_W: 'Arena width, in units', ARENA_H: 'Arena height, in units', ROBOT_RADIUS: 'Circular collision radius, in units',
  MAX_HEALTH: 'Starting health', CYCLES_PER_TICK: 'Maximum CPU cycles per robot per tick', NUM_REGS: 'Number of registers',
  MEMORY_SIZE: 'Memory words', STACK_SIZE: 'Shared data/return stack entries', MAX_SPEED: 'Maximum forward units per tick',
  MAX_REVERSE: 'Minimum signed speed, in units per tick', ACCELERATION: 'Maximum speed change per tick',
  BODY_TURN_RATE: 'Maximum body degrees per tick', TURRET_TURN_RATE: 'Maximum turret degrees per tick',
  FIRE_COOLDOWN: 'Minimum ticks between shots', BULLET_SPEED: 'Projectile units per tick', BULLET_DAMAGE: 'Health lost per projectile hit',
  SCAN_MAX_WIDTH: 'Maximum full scan-cone width, in degrees',
  SCAN_RANGE_FACTOR: 'Scan reach = floor(factor / √width), in units; narrow cones reach farther',RADAR_RANGE: 'Maximum radar distance, in units',
  MAX_TICKS: 'Competitive match time limit, in ticks',
};
for (const [k, v] of Object.entries(C)) out.push(`| \`${k}\` | ${v} | ${meanings[k] || ''} |`);
out.push('', `At 0 health a robot is destroyed. In free-for-all, the last living robot wins; at the time limit, the living robot with highest health wins, with an equal-health tie producing a draw. Team matches use the last surviving team or highest total living-team health, with a tie producing a draw. Browser practice without an opponent has no victory/time-limit check; the CLI stops practice runs after ${C.MAX_TICKS} ticks.`);
out.push('');
fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs', 'LANGUAGE.md'), out.join('\n'));
console.log(`Wrote ${BB.EXAMPLES.length} examples and docs/LANGUAGE.md`);
